### ISSUE TITLE
Error when any code interacts with the Wallrun ability

### ISSUE THREAD

**Issue by HappyHippo77** [Aztlon/JedCore#6]
Not much to say, I'm not the best at reading reports, but I can get the idea.

> [02:53:03] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to JedCore v2.9.6.1-Spigot1.18-PK1.9.3
> org.bukkit.event.EventException: null
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:504) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:471) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:187) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1466) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:34) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:8) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at net.minecraft.network.protocol.PlayerConnectionUtils$$Lambda$5732/0x0000000044d81b80.run(Unknown Source) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at net.minecraft.server.TickTask.run(SourceFile:18) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1125) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at net.minecraft.server.MinecraftServer$$Lambda$3882/0x0000000041d55258.run(Unknown Source) [spigot.jar:3284a-Spigot-3892929-0ab8487]
>         at java.lang.Thread.run(Thread.java:853) [?:?]
> Caused by: java.lang.NoSuchFieldError: com/projectkorra/projectkorra/Element.CHI
>         at com.jedk1.jedcore.ability.passive.WallRun.isEligible(WallRun.java:101) ~[?:?]
>         at com.jedk1.jedcore.ability.passive.WallRun.<init>(WallRun.java:65) ~[?:?]
>         at com.jedk1.jedcore.listener.AbilityListener.onPlayerSwing(AbilityListener.java:176) ~[?:?]
>         at jdk.internal.reflect.GeneratedMethodAccessor114.invoke(Unknown Source) ~[?:?]
>         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
>         at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
>         ... 23 more

**Comment by Aztlon** [comment]
This has been resolved as of 2.9.6.2.
